### ISSUE TITLE
メイン画面を新規作成する

### ISSUE THREAD

**Issue by takyafumin** [sassy-baby/AllergyChecker#3]
メイン画面を新規作成する。
- 背景は真っ白
- 画面下部にタブバーを配置する。

タブバーの要素は以下、それぞれ分かりやすいアイコンで作成。
- アレルギー
- こんだて
- 名簿
- 設定

**Comment by sassy-baby** [comment]
タブバーの設置完了。
背景色を白に変更の調査を行う。

**Comment by takyafumin** [comment]
普通にdivタグとcssで出来ないかなぁ？

**Comment by sassy-baby** [comment]
divとcssで要素（リスト）等の背景色は変更が可能。
要素等がないもないところの変更は別途調査が必要だが、現状はこのままでいくこととする。
